# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path: admin_logout
                # Si vous avez une page cible après la déconnexion, spécifiez-la ici
                # target: /
            entry_point: App\Security\UserAuthenticator

    access_control:
        # Permet l'accès anonyme à /home
        - { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Permet l'accès anonyme à /login
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Accès restreint à /admin et sous-répertoires aux utilisateurs avec le rôle ROLE_ADMIN
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Accès restreint aux autres chemins aux utilisateurs authentifiés
        - { path: ^/, roles: ROLE_USER }
