controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# admin_dashboard:
#     path: /admin/dashboard
#     controller: App\Controller\Admin\AdminController::index

# home:
#     path: /
#     controller: App\Controller\HomeController::index