controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login:
    path: /login
    controller: App\Controller\SecurityController::login

home:
    path: /home
    controller: App\Controller\HomeController::index