# config/services.yaml

services:
    App\Security\UserAuthenticator:
        arguments:
            - '@router'
            - '@request_stack'

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path: logout
                target: /
            # Pas de point d'entrée spécifique nécessaire ici si la redirection est gérée
            # par l'authenticator ou si le formulaire de connexion est configuré correctement

    