# config/services.yaml

services:
    # ...

    # Déclaration du service UserAuthenticator
    App\Security\UserAuthenticator:
        arguments:
            - '@router'          # Injection du service Router
            - '@request_stack'   # Injection du service RequestStack

    # Déclaration du service pour votre entité User si ce n'est pas déjà fait
    # Assurez-vous que ce service est correctement configuré pour être utilisé dans la configuration de sécurité
    App\Repository\UserRepository:
        autowire: true
        autoconfigure: true
        public: false

    # Autres services...

    # Si vous utilisez le provider d'utilisateurs en mémoire pour des tests ou des exemples
    # et que vous avez défini un fournisseur d'utilisateurs en mémoire
    in_memory_user_provider:
        class: Symfony\Component\Security\Core\User\InMemoryUserProvider
        arguments:
            - 
                users:
                    user:
                        password: '%env(resolve:USER_PASSWORD)%'
                        roles: ['ROLE_USER']
                    admin:
                        password: '%env(resolve:ADMIN_PASSWORD)%'
                        roles: ['ROLE_ADMIN']

    # ...

    # Vous pouvez également configurer d'autres services nécessaires à votre application ici
